import Header from '@/components/layout/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className='w-[min-content] mt-20 max-w-6xl mx-auto'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
